CREATE TABLE IF NOT EXISTS 'Users'(
	'Id' INT NOT NULL AUTO_INCREMENT,
	`email` varchar(100) NOT NULL AUTO_INCREMENT,
	`name` varchar(100) NOT NULL AUTO_INCREMENT,
	`passwd` varchar(100) NOT NULL AUTO_INCREMENT,
	`role` INT(100) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`Id`)
);

CREATE TABLE IF NOT EXISTS `Tasks` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(255) NOT NULL AUTO_INCREMENT,
	`user` INT NOT NULL AUTO_INCREMENT,
	`due.date` DATETIME NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `Roles` (
	`id` INT NOT NULL,
	`role` INT NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `Tasks_Item` (
	`Id` INT NOT NULL AUTO_INCREMENT,
	`Item` VARCHAR(255) NOT NULL AUTO_INCREMENT,
	`completed` BOOLEAN NOT NULL AUTO_INCREMENT,
	`task` INT NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`Id`)
);

ALTER TABLE `Users` ADD CONSTRAINT `Users_fk0` FOREIGN KEY (`role`) REFERENCES `Roles`(`id`);

ALTER TABLE `Tasks` ADD CONSTRAINT `Tasks_fk0` FOREIGN KEY (`id`) REFERENCES `Tasks_Item`(`task`);

